# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  POSTGRES_DB: YXBwX2Ri # base64 encoded "app_db"
  POSTGRES_USER: YXBwX3VzZXI= # base64 encoded "app_user"
  POSTGRES_PASSWORD: YXBwX3Bhc3M= # base64 encoded "app_pass"